---
- name: Install Docker and Run Flask App
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Build Flask app Docker image
      docker_image:
        name: flask-app
        build:
          path: /home/ubuntu/flask-app

    - name: Run Flask app container
      docker_container:
        name: flask-app
        image: flask-app
        state: started
        published_ports:
          - "5000:5000"

